config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/search', to: 'searches#search'
    resources :schedules, only: [:index, :show, :edit, :update, :destroy]
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  namespace :public do
    get 'end_user/worked'
  end
  scope module: :public do
    get 'end_users/search', to: 'searches#search'
    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
    end
    root 'homes#top'
    get 'about' => "homes#about"
    resources :end_users, only: [] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'end_users/users/attends/:id' => 'attends#index', as: 'attend_index'
    get 'end_users/users/:id' => 'end_users#show', as: 'user_page'
    get 'end_users/users' => 'end_users#index', as: 'user_index'
    get 'end_users/users/index/:id' => 'end_users#schedule_index', as: 'user_schedule'
    # end_users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/information/edit/:id' => 'end_users#edit', as: 'edit_information'
    patch 'end_users/information' => 'end_users#update', as: 'update_information'
    patch 'end_users/users' => 'end_users#worked', as: 'update_worked'
    resources :schedules, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resources :schedule_comments, only: [:create, :destroy]
      resources :reports, only: [:create, :destroy]
      resource :attends, only: [:index, :create, :destroy]
    end
  end
  devise_for :end_users,skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }
  
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def search
    @model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'end_user'
			@records = EndUser.search_for(@content, @method)
		else
			@records = Schedule.search_for(@content, @method)
		end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/search.html.erb
<% if @model == 'end_user' %>
	<h3>EndUser search for "<%= @content %>"</h3>
  <div class='container'>
  <div class='row'>
    <div class='col-3'>
      <h2>User info</h2>
    </div>
    <div class='col-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>部署名</th>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |end_user| %>
      <% if end_user.full_name != "guest user" %>
        <tr>
          <td><%= link_to admin_end_user_path(end_user) do %><%= image_tag end_user.get_profile_image, size: '50x50' %><% end %></td>
          <td><%= link_to admin_end_user_path(end_user) do %><%= end_user.department_name %><% end %></td>
          <td><%= link_to admin_end_user_path(end_user) do %><%= end_user.full_name %><% end %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
      </table>
    </div>
  </div>
</div>
<% elsif @model == 'schedule' %>
<div class='container'>
  <div class='row'>
    <div class='col-3'>
      <h2>User info</h2>
    </div>
    <div class='col-8 offset-md-1'>
      <h2>予定一覧</h2>
      <table class='table'>
  <thead>
    <tr>
      <th>予定日</th>
      <th>タイトル</th>
      <th>所属部署</th>
      <th>作成者</th>
    </tr>
  </thead>
  <tbody>
    <% @records.each do |schedule| %>
      <tr>
        <td><%= link_to admin_schedule_path(schedule) do %><%= schedule.full_day %><% end %></td>
        <td><%= link_to admin_schedule_path(schedule) do %><%= schedule.title %><% end %></td>
        <td><%= link_to admin_schedule_path(schedule) do %><%= schedule.end_user.department_name %><% end %></td>
        <td><%= link_to admin_schedule_path(schedule) do %><%= schedule.end_user.full_name %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>
<% end %> 