config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/search', to: 'searches#search'
    resources :schedules, only: [:index, :show, :edit, :update, :destroy]
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  namespace :public do
    get 'end_user/worked'
  end
  scope module: :public do
    get 'end_users/search', to: 'searches#search'
    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
    end
    root 'homes#top'
    get 'about' => "homes#about"
    resources :end_users, only: [] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'end_users/users/attends/:id' => 'attends#index', as: 'attend_index'
    get 'end_users/users/:id' => 'end_users#show', as: 'user_page'
    get 'end_users/users' => 'end_users#index', as: 'user_index'
    get 'end_users/users/index/:id' => 'end_users#schedule_index', as: 'user_schedule'
    # end_users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/information/edit/:id' => 'end_users#edit', as: 'edit_information'
    patch 'end_users/information' => 'end_users#update', as: 'update_information'
    patch 'end_users/users' => 'end_users#worked', as: 'update_worked'
    resources :schedules, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resources :schedule_comments, only: [:create, :destroy]
      resources :reports, only: [:create, :destroy]
      resource :attends, only: [:index, :create, :destroy]
    end
  end
  devise_for :end_users,skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }
  
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :schedules, dependent: :destroy
  has_many :schedule_comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :attends, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true
  validates :department_name, presence: true
  validates :work_location, presence: true
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }
  
  has_one_attached :profile_image
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def full_name
    first_name + " " + last_name
  end

  def full_name_kana
    first_name_kana + " " + last_name_kana
  end
  
  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end
  # フォローを外すときの処理
  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end
  # フォローしているか判定
  def following?(end_user)
    followings.include?(end_user)
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      EndUser.where(first_name: content)
    elsif method == 'forward'
      EndUser.where('first_name LIKE ?', content + '%')
    elsif method == 'backward'
      EndUser.where('first_name LIKE ?', '%' + content)
    else
      EndUser.where('first_name LIKE ?', '%' + content + '%')
    end
  end
  
  def self.guest
    find_or_create_by!(first_name: 'guest', last_name: 'user', first_name_kana: 'ゲスト', last_name_kana: 'ユーザー'  , email: 'guest@example.com', department_name: '情報システム部', work_location: '本部支店', telephone_number: '00011112222') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      end_user.first_name = "guest"
      end_user.last_name = "user"
      end_user.first_name_kana = "ゲスト"
      end_user.last_name_kana = "ユーザー"
      end_user.email = "guest@example.com"
      end_user.department_name = "情報システム部"
      end_user.work_location = "本部支店"
      end_user.telephone_number = "00011112222"
    end
  end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :ensure_end_user, only: [:show, :edit, :update]
  
  def index
    @end_users = EndUser.all
  end

  def show
  end

  def edit
  end

  def update
    @end_user.update(end_user_params) ? (redirect_to admin_end_user_path(@end_user)) : (render :edit)
  end
  
  private
  
  def end_user_params
    params.require(:end_user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :email, :department_name, :work_location, :telephone_number, :profile_image, :is_worked, :is_deleted)
  end
  
  def ensure_end_user
    @end_user = EndUser.find(params[:id])
  end
  
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<section class="inner">
	<h2 class="section-ttl"><%= @end_user.first_name %> <%= @end_user.last_name %> さんの会員情報編集</h2>
	<%= form_with model:@end_user, url: admin_end_user_path(@end_user) do |f| %>
		<table class="end_user_info end_user_form">
			<thead>
				<th></th>
				<th></th>
				<th></th>
			</thead>
			<tbody>
				<tr>
					<td>名前</td>
					<td><%= f.label :first_name, "(姓)", class: "end_user_name" %> <%= f.text_field :first_name, :placeholder =>"#{@end_user.first_name}" %></td>
					<td><%= f.label :last_name, "(名)", class: "end_user_name" %> <%= f.text_field :last_name, :placeholder =>"#{@end_user.last_name}" %></td>
				</tr>
				<tr>
					<td>フリガナ</td>
					<td><%= f.label :first_name_kana, "(セイ)" %> <%= f.text_field :first_name_kana, :placeholder =>"#{@end_user.first_name_kana}" %></td>
					<td><%= f.label :last_name_kana, "(メイ)" %> <%= f.text_field :last_name_kana, :placeholder =>"#{@end_user.last_name_kana}" %></td>
				</tr>
				<tr>
					<td>メールアドレス</td>
					<td colspan="2"><%= f.email_field :email, autocomplete: "email", :placeholder =>"#{@end_user.email}" %></td>
				</tr>
				<tr>
					<td>部署名</td>
					<td colspan="2"><%= f.text_field :department_name, :placeholder =>"#{@end_user.department_name}" %></td>
				</tr>
				<tr>
					<td>勤務地</td>
					<td colspan="2"><%= f.text_field :work_location, :placeholder =>"#{@end_user.work_location}" %></td>
				</tr>
				<tr>
					<td>会員ステータス</td>
					<td><%= f.radio_button :is_deleted, true %><%= f.label :is_deleted, "有効", class: "text-deleted" %></td>
					<td><%= f.radio_button :is_deleted, false %><%= f.label :is_deleted, "利用停止", class: "text-invalid" %></td>
				</tr>
				<tr>
					<td colspan="3"><%= f.submit "更新", class: "btn btn-primary" %></td>
				</tr>
			</tbody>
		</table>
	<% end %>
</section>

app/views/admin/end_users/index.html.erb
<section class="inner">
	<h2 class="section-ttl">会員一覧</h2>
	<%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "EndUser" => "end_user", "Schedule" => "schedule" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
	<table class="admin_end_user_index has_border">
	<thead>
		<th>会員ID</th>
		<th>所属部署</th>
		<th>名前</th>
		<th>出勤状況</th>
		<th>会員ステータス</th>
		<th></th>
	</thead>
	<tbody>
		<% @end_users.each do |end_user| %>
			<tr>
				<td><%= end_user.id %></td>
				<td><%= end_user.department_name %></td>
				<td><%= end_user.full_name %></td>
				<td>
					<% if end_user.is_worked? %>
						<span class="text-active">出勤中</span>	
					<% else %>
						<span class="text-invalid">退勤中</span>
					<% end %>
				</td>
				<td>
					<% if end_user.is_deleted? %>
						<span class="text-active">有効</span>	
					<% else %>
						<span class="text-invalid">利用停止</span>
					<% end %>
				</td>
				<td><%= link_to "詳細", admin_end_user_path(end_user), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</tbody>
</table>
</section>
<%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
<%= link_to 'スケジュール一覧', admin_schedules_path %>

app/views/admin/end_users/show.html.erb
<section class="inner">
	<h2 class="section-ttl"><%= @end_user.full_name %>さんのページ</h2>
	<table class="end_user_info">
		<thead>
			<th></th>
			<th></th>
			<th></th>
		</thead>
		<tbody>
			<tr>
				<td>会員ID</td>
				<td colspan="2"><%= @end_user.id %></td>
			</tr>
			<tr>
				<td>名前</td>
				<td>(姓) <%= @end_user.first_name %></td>
				<td>(名) <%= @end_user.last_name %></td>
			</tr>
			<tr>
				<td>フリガナ</td>
				<td>(セイ) <%= @end_user.first_name_kana %></td>
				<td>(メイ) <%= @end_user.last_name_kana %></td>
			</tr>
			<tr>
				<td>所属部署</td>
				<td colspan="2"><%= @end_user.department_name %></td>
			</tr>
			<tr>
				<td>勤務地</td>
				<td colspan="2"><%= @end_user.work_location %></td>
			</tr>
			<tr>
				<td>電話番号</td>
				<td colspan="2"><%= @end_user.telephone_number %></td>
			</tr>
			<tr>
				<td>メールアドレス</td>
				<td colspan="2"><%= @end_user.email %></td>
			</tr>
			<tr>
			  <td>出勤状況</td>
				<td>
					<% if @end_user.is_worked? %>
						<span class="text-active">出勤中</span>	
					<% else %>
						<span class="text-invalid">退勤中</span>
					<% end %>
				</td>
			</tr>
			<tr>
			  <td>会員ステータス</td>
			  <td>
			    <% if @end_user.is_deleted? %>
						<span class="text-active">有効</span>	
					<% else %>
						<span class="text-invalid">利用停止</span>
					<% end %>
				</td>
			</tr>
			<tr>
				<td><%= link_to "編集", edit_admin_end_user_path(@end_user), class: "btn btn-success" %></td>
			</tr>
		</tbody>
	</table>
	
</section>

app/views/admin/end_users/update.html.erb
<h1>Admin::EndUsers#update</h1>
<p>Find me in app/views/admin/end_users/update.html.erb</p>