config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/search', to: 'searches#search'
    resources :schedules, only: [:index, :show, :edit, :update, :destroy]
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  namespace :public do
    get 'end_user/worked'
  end
  scope module: :public do
    get 'end_users/search', to: 'searches#search'
    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
    end
    root 'homes#top'
    get 'about' => "homes#about"
    resources :end_users, only: [] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'end_users/users/attends/:id' => 'attends#index', as: 'attend_index'
    get 'end_users/users/:id' => 'end_users#show', as: 'user_page'
    get 'end_users/users' => 'end_users#index', as: 'user_index'
    get 'end_users/users/index/:id' => 'end_users#schedule_index', as: 'user_schedule'
    # end_users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/information/edit/:id' => 'end_users#edit', as: 'edit_information'
    patch 'end_users/information' => 'end_users#update', as: 'update_information'
    patch 'end_users/users' => 'end_users#worked', as: 'update_worked'
    resources :schedules, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resources :schedule_comments, only: [:create, :destroy]
      resources :reports, only: [:create, :destroy]
      resource :attends, only: [:index, :create, :destroy]
    end
  end
  devise_for :end_users,skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }
  
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :end_user
  has_many :schedule_comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :attends, dependent: :destroy
  
  has_one_attached :schedule_image
  
  def get_schedule_image
    (schedule_image.attached?) ? schedule_image : 'default_image.jpg'
  end
  
  def full_day
    year.to_s + "年" + month.to_s + "月" + day.to_s + "日"
  end
  
  def attended?(end_user)
    attends.where(end_user_id: end_user.id).exists?
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      Schedule.where(title: content)
    elsif method == 'forward'
      Schedule.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Schedule.where('title LIKE ?', '%'+content)
    else
      Schedule.where('title LIKE ?', '%'+content+'%')
    end
  end
  
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def show
    @schedule = Schedule.find(params[:id])
    @schedule_comments = @schedule.schedule_comments
    @reports = @schedule.reports
    @attends = @schedule.attends
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to admin_schedule_path(@schedule.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to admin_schedules_path
  end

  private
  def schedule_params
    params.require(:schedule).permit(:title, :schedule_image, :body, :year, :month, :day, :location)
  end
end

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
end

app/views/admin/schedules/edit.html.erb
<section class="inner">
	<h2 class="section-ttl">予定編集</h2>
	<%= form_with model:@schedule, url:admin_schedule_path(@schedule), local:true do |f| %>
	<h4>タイトル</h4>
    <%= f.text_field :title, :placeholder =>"#{@schedule.title}"%>
    <h4>画像</h4>
    <%= f.file_field :schedule_image, accept: "image/*" %>
    <h4>説明</h4>
    <%= f.text_area :body,:placeholder =>"#{@schedule.body}" %>
    <h4>年</h4>
    <%= f.select :year, [['2022', 2022], ['2023', 2023], ['2024', 2024], ['2025', 2025], ['2026', 2026]], { include_blank: true, selected: 1 }, { id: "month", class: "month_class" } %>
    <h4>月</h4>
    <%= f.select :month, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10], ['11', 11], ['12', 12]], { include_blank: true, selected: 1 }, { id: "month", class: "month_class" } %>
    <h4>日</h4>
    <%= f.select :day, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10], ['11', 11], ['12', 12], ['13', 13], ['14', 14], ['15', 15], ['16', 16], ['17', 17], ['18', 18], ['19', 19], ['20', 20], ['21', 21], ['22', 22], ['23', 23], ['24', 24], ['25', 25], ['26', 26], ['27', 27], ['28', 28], ['29', 29], ['30', 30], ['31', 31]], { include_blank: true, selected: 1 }, { id: "day", class: "day_class" } %>
    <h4>場所</h4>
    <%= f.text_area:location, :placeholder =>"#{@schedule.location}" %>
    <%= f.submit '投稿' %>
	<% end %>
	<%= link_to "削除", admin_schedule_path(@schedule), method: :delete %>
</section>

app/views/admin/schedules/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-3'>
      <h2>User info</h2>
    </div>
    <div class='col-8 offset-md-1'>
      <h2>予定一覧</h2>
      <table class='table'>
  <thead>
    <tr>
      <th>予定日</th>
      <th>タイトル</th>
      <th>所属部署</th>
      <th>作成者</th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= link_to admin_schedule_path(schedule.id) do %><%= schedule.full_day %><% end %></td>
        <td><%= link_to admin_schedule_path(schedule.id) do %><%= schedule.title %><% end %></td>
        <td><%= link_to admin_schedule_path(schedule.id) do %><%= schedule.end_user.department_name %><% end %></td>
        <td><%= link_to admin_schedule_path(schedule.id) do %><%= schedule.end_user.full_name %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/admin/schedules/show.html.erb
<div class='container'>
<div class='row'>
<div class='col-3'>
	<%= link_to "社員一覧",user_index_path %>
	<%= link_to "予定投稿",new_schedule_path %>
</div>
<div class="col-8">
	<section class="inner">
		<h1><%= @schedule.title %></h1>
		<a><%= image_tag @schedule.get_schedule_image, size: '200x250' %></a>
		<p><%= @schedule.body %></p>
		<p><%= @schedule.full_day %></p>
		<p><%= @schedule.location %></p>
		<%= link_to "編集", edit_admin_schedule_path(@schedule.id) %>
    <p>コメント</p>
    <% @schedule_comments.each do |schedule_comment| %>
    	<%= schedule_comment.end_user.full_name %>
      <%= schedule_comment.comment %>
      <%= link_to "削除", schedule_schedule_comment_path(@schedule, schedule_comment), method: :delete %>
    <% end %>
    <p>報告</p>
    <% @reports.each do |report| %>
    	<%= report.end_user.full_name %>
      <%= report.comment %>
      <%= link_to "削除", schedule_report_path(@schedule, report), method: :delete %>
    <% end %>
    <p>参加者</p>
    <% @attends.each do |attend| %>
      <%= attend.end_user.full_name %>
    <% end %>
	</section>
</div>
</div>
</div>

app/views/admin/schedules/update.html.erb
<h1>Admin::Schedules#update</h1>
<p>Find me in app/views/admin/schedules/update.html.erb</p>