config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/search', to: 'searches#search'
    resources :schedules, only: [:index, :show, :edit, :update, :destroy]
    resources :end_users, only: [:index, :show, :edit, :update]
  end

  namespace :public do
    get 'end_user/worked'
  end
  scope module: :public do
    get 'end_users/search', to: 'searches#search'
    devise_scope :end_user do
      post 'end_users/guest_sign_in', to: 'end_users/sessions#guest_sign_in'
    end
    root 'homes#top'
    get 'about' => "homes#about"
    resources :end_users, only: [] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    get 'end_users/users/attends/:id' => 'attends#index', as: 'attend_index'
    get 'end_users/users/:id' => 'end_users#show', as: 'user_page'
    get 'end_users/users' => 'end_users#index', as: 'user_index'
    get 'end_users/users/index/:id' => 'end_users#schedule_index', as: 'user_schedule'
    # end_users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/information/edit/:id' => 'end_users#edit', as: 'edit_information'
    patch 'end_users/information' => 'end_users#update', as: 'update_information'
    patch 'end_users/users' => 'end_users#worked', as: 'update_worked'
    resources :schedules, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
      resources :schedule_comments, only: [:create, :destroy]
      resources :reports, only: [:create, :destroy]
      resource :attends, only: [:index, :create, :destroy]
    end
  end
  devise_for :end_users,skip: [:passwords], controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }
  
  devise_for :admin, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html..erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    Copyright © Infratop Inc. All Rights Reserved.
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="/"><h4 class="pt-2 font-weight-bold">Appoint Share</span></h4></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" -controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if end_user_signed_in? %>
        <li class='pt-2 pr-3'>
          <%= form_with url: end_users_search_path, method: :get, local: true do |f| %>
          <%= f.text_field :content %>
          <%= f.select :model, options_for_select({ "EndUser" => "end_user", "Schedule" => "schedule" }) %>
          <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
          <%= f.submit '検索' %>
          <% end %>
        </li>
        <li>
          <%= link_to user_page_path(current_end_user),class: 'nav-link text-dark' do %>
            マイページ
          <% end %>
        </li> 
        <li>
          <%=  link_to user_schedule_path(current_end_user),class: 'nav-link text-dark' do %>
            投稿した予定
          <% end %>
        </li>
        <li>
          <%=  link_to attend_index_path(current_end_user),class: 'nav-link text-dark' do %>
            参加予定
          <% end %>
        </li>
        <li>
          <%= link_to end_user_followings_path(current_end_user),class: 'nav-link text-dark' do %>
            連携社員
          <% end %>
        </li>
        <li>
          <%= link_to destroy_end_user_session_path,method: :delete,class: 'nav-link text-dark' do %>
            ログアウト
          <% end %>
        </li>
      <% elsif admin_signed_in? %>
        <li>
          <%= link_to admin_schedules_path,class: 'nav-link text-dark' do %>
            社員一覧
          <% end %>
        </li>
        <li>
          <%= link_to admin_end_users_path,class: 'nav-link text-dark' do %>
            社員一覧
          <% end %>
        </li>
        <li>
          <%= link_to destroy_admin_session_path,method: :delete,class: 'nav-link text-dark' do %>
            ログアウト
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to root_path,class: 'nav-link text-dark' do %>
            HOME
          <% end %>
        </li>
        <li>
          <%= link_to about_path,class: 'nav-link text-dark' do %>
            ABOUT
          <% end %>
        </li>
        <li>
          <%= link_to new_end_user_registration_path,class: 'nav-link text-dark' do %>
           新規登録
          <% end %>
        </li>
        <li>
          <%= link_to new_end_user_session_path ,class: 'nav-link text-dark' do %>
           ログイン
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-content">
        <%= render 'layouts/header' %>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
        Copyright © Infratop Inc. All Rights Reserved.
    </footer>
  </body>
</html>